description: Connects to Prometheus metrics and data through the Model Context
  Protocol (MCP), providing access to metric schemas and detailed metadata,
  along with statistical information.
skills:
  - List Prometheus metrics
  - Access metric schema
  - Retrieve metric details
  - Provide statistical information (count, min, max)
  - Return data in JSON format
