description: Retrieve and analyze metric data from Prometheus databases, execute
  advanced PromQL queries, and explore usage patterns with enhanced control over
  analysis tasks.
skills:
  - Fetch specific metrics or data ranges
  - Perform statistical analysis on metrics
  - Search and explore metric usage patterns
  - Execute complex PromQL queries
