description: An interactive demo site for exploring Netlify features, allowing
  users to quickly deploy their own version and access related tutorials. It
  provides a hands-on way to learn about web development enhancements using
  Netlify.
skills:
  - Deploy web projects
  - Access documentation
  - Follow tutorials
  - Clone GitHub repositories
