identifier: kyungwoo007/netlify-feature-tour/netlify-feature-tour
repo:
  provider: github.com
  url: https://github.com/kyungwoo007/netlify-feature-tour
  name: netlify-feature-tour
  owner: kyungwoo007
server:
  subdirectory: /
  name: Feature Tour
  description: Explore and learn about Netlify features through an interactive
    demo site. Quickly deploy your own version to see how Netlify can enhance
    your web projects. Get started with easy-to-follow tutorials and local
    development setup.
  flags:
    isOfficial: false
    isCommunity: true
    isHostable: false
