identifier: docker/hub-mcp
repo:
  provider: github.com
  url: https://github.com/docker/hub-mcp
  name: hub-mcp
  owner: docker
server:
  subdirectory: /
  name: Hub Mcp
  description: "Docker MCP server for hub-mcp operations."
  flags:
    isOfficial: false
    isCommunity: true
    isHostable: true
