description: Interact with Netlify to manage and deploy sites using the CLI,
  handling tasks such as managing environment variables and build processes.
skills:
  - Deploy sites
  - Manage environment variables
  - Handle builds
  - Interact with Netlify CLI
