identifier: dynamicendpoints/netlify-mcp-server/netlify-mcp-server
repo:
  provider: github.com
  url: https://github.com/DynamicEndpoints/Netlify-MCP-Server
  name: Netlify-MCP-Server
  owner: DynamicEndpoints
server:
  subdirectory: /
  name: Netlify MCP Server
  description: Manage and deploy your Netlify sites effortlessly.
  flags:
    isOfficial: false
    isCommunity: true
    isHostable: true
