description: Docker-based MCP server designed for managing operations within
  Kubernetes environments. It enables seamless integration of AI models with
  various tools and data sources through the Model Context Protocol.
skills:
  - Manage Kubernetes operations
  - Integrate with Docker
  - Support for Bun runtime
  - Execute containerized applications
