identifier: grafana/mcp-grafana
repo:
  provider: github.com
  url: https://github.com/grafana/mcp-grafana
  name: mcp-grafana
  owner: grafana
server:
  subdirectory: /
  name: Mcp Grafana
  description: "Docker MCP server for mcp-grafana operations."
  flags:
    isOfficial: false
    isCommunity: true
    isHostable: true
